/* 
 * Qa full api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: all
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;

namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing Availability
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AvailabilityTests
    {
        // TODO uncomment below to declare an instance variable for Availability
        //private Availability instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Availability
            //instance = new Availability();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Availability
        /// </summary>
        [Test]
        public void AvailabilityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Availability
            //Assert.IsInstanceOfType<Availability> (instance, "variable 'instance' is a Availability");
        }

        /// <summary>
        /// Test the property 'AcceptReservations'
        /// </summary>
        [Test]
        public void AcceptReservationsTest()
        {
            // TODO unit test for the property 'AcceptReservations'
        }
        /// <summary>
        /// Test the property 'AvailabilityLevel'
        /// </summary>
        [Test]
        public void AvailabilityLevelTest()
        {
            // TODO unit test for the property 'AvailabilityLevel'
        }
        /// <summary>
        /// Test the property 'InWaitCovers'
        /// </summary>
        [Test]
        public void InWaitCoversTest()
        {
            // TODO unit test for the property 'InWaitCovers'
        }
        /// <summary>
        /// Test the property 'MaxCoversForSlot'
        /// </summary>
        [Test]
        public void MaxCoversForSlotTest()
        {
            // TODO unit test for the property 'MaxCoversForSlot'
        }
        /// <summary>
        /// Test the property 'Open'
        /// </summary>
        [Test]
        public void OpenTest()
        {
            // TODO unit test for the property 'Open'
        }
        /// <summary>
        /// Test the property 'RecommendedTables'
        /// </summary>
        [Test]
        public void RecommendedTablesTest()
        {
            // TODO unit test for the property 'RecommendedTables'
        }
        /// <summary>
        /// Test the property 'RequestedTime'
        /// </summary>
        [Test]
        public void RequestedTimeTest()
        {
            // TODO unit test for the property 'RequestedTime'
        }
        /// <summary>
        /// Test the property 'ReservedCovers'
        /// </summary>
        [Test]
        public void ReservedCoversTest()
        {
            // TODO unit test for the property 'ReservedCovers'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }

    }

}
