/* 
 * Qa full api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: all
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;

namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing AvailabilityResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AvailabilityResponseTests
    {
        // TODO uncomment below to declare an instance variable for AvailabilityResponse
        //private AvailabilityResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AvailabilityResponse
            //instance = new AvailabilityResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AvailabilityResponse
        /// </summary>
        [Test]
        public void AvailabilityResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AvailabilityResponse
            //Assert.IsInstanceOfType<AvailabilityResponse> (instance, "variable 'instance' is a AvailabilityResponse");
        }

        /// <summary>
        /// Test the property 'Availabilities'
        /// </summary>
        [Test]
        public void AvailabilitiesTest()
        {
            // TODO unit test for the property 'Availabilities'
        }
        /// <summary>
        /// Test the property 'RequestedTime'
        /// </summary>
        [Test]
        public void RequestedTimeTest()
        {
            // TODO unit test for the property 'RequestedTime'
        }
        /// <summary>
        /// Test the property 'TotalCovers'
        /// </summary>
        [Test]
        public void TotalCoversTest()
        {
            // TODO unit test for the property 'TotalCovers'
        }
        /// <summary>
        /// Test the property 'TotalReservationCovers'
        /// </summary>
        [Test]
        public void TotalReservationCoversTest()
        {
            // TODO unit test for the property 'TotalReservationCovers'
        }
        /// <summary>
        /// Test the property 'TotalWaitCovers'
        /// </summary>
        [Test]
        public void TotalWaitCoversTest()
        {
            // TODO unit test for the property 'TotalWaitCovers'
        }
        /// <summary>
        /// Test the property 'UnitType'
        /// </summary>
        [Test]
        public void UnitTypeTest()
        {
            // TODO unit test for the property 'UnitType'
        }

    }

}
