/* 
 * Qa full api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: all
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;

namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing LoyaltySettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoyaltySettingsTests
    {
        // TODO uncomment below to declare an instance variable for LoyaltySettings
        //private LoyaltySettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoyaltySettings
            //instance = new LoyaltySettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoyaltySettings
        /// </summary>
        [Test]
        public void LoyaltySettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoyaltySettings
            //Assert.IsInstanceOfType<LoyaltySettings> (instance, "variable 'instance' is a LoyaltySettings");
        }

        /// <summary>
        /// Test the property 'CheckinPoints'
        /// </summary>
        [Test]
        public void CheckinPointsTest()
        {
            // TODO unit test for the property 'CheckinPoints'
        }
        /// <summary>
        /// Test the property 'IsEnabled'
        /// </summary>
        [Test]
        public void IsEnabledTest()
        {
            // TODO unit test for the property 'IsEnabled'
        }
        /// <summary>
        /// Test the property 'MembershipLevelRules'
        /// </summary>
        [Test]
        public void MembershipLevelRulesTest()
        {
            // TODO unit test for the property 'MembershipLevelRules'
        }
        /// <summary>
        /// Test the property 'PurchasePointsRules'
        /// </summary>
        [Test]
        public void PurchasePointsRulesTest()
        {
            // TODO unit test for the property 'PurchasePointsRules'
        }
        /// <summary>
        /// Test the property 'SignupPoints'
        /// </summary>
        [Test]
        public void SignupPointsTest()
        {
            // TODO unit test for the property 'SignupPoints'
        }
        /// <summary>
        /// Test the property 'WaitingPointsRules'
        /// </summary>
        [Test]
        public void WaitingPointsRulesTest()
        {
            // TODO unit test for the property 'WaitingPointsRules'
        }

    }

}
