/* 
 * Qa full api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: all
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;

namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing RedeemRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RedeemRequestTests
    {
        // TODO uncomment below to declare an instance variable for RedeemRequest
        //private RedeemRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RedeemRequest
            //instance = new RedeemRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RedeemRequest
        /// </summary>
        [Test]
        public void RedeemRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RedeemRequest
            //Assert.IsInstanceOfType<RedeemRequest> (instance, "variable 'instance' is a RedeemRequest");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Submited'
        /// </summary>
        [Test]
        public void SubmitedTest()
        {
            // TODO unit test for the property 'Submited'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusComment'
        /// </summary>
        [Test]
        public void StatusCommentTest()
        {
            // TODO unit test for the property 'StatusComment'
        }
        /// <summary>
        /// Test the property 'Closed'
        /// </summary>
        [Test]
        public void ClosedTest()
        {
            // TODO unit test for the property 'Closed'
        }
        /// <summary>
        /// Test the property 'RewardId'
        /// </summary>
        [Test]
        public void RewardIdTest()
        {
            // TODO unit test for the property 'RewardId'
        }
        /// <summary>
        /// Test the property 'TableNumber'
        /// </summary>
        [Test]
        public void TableNumberTest()
        {
            // TODO unit test for the property 'TableNumber'
        }
        /// <summary>
        /// Test the property 'MemberInfo'
        /// </summary>
        [Test]
        public void MemberInfoTest()
        {
            // TODO unit test for the property 'MemberInfo'
        }
        /// <summary>
        /// Test the property 'RewardDetails'
        /// </summary>
        [Test]
        public void RewardDetailsTest()
        {
            // TODO unit test for the property 'RewardDetails'
        }

    }

}
