/* 
 * Qa full api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: all
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;

namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing TableUserInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TableUserInfoTests
    {
        // TODO uncomment below to declare an instance variable for TableUserInfo
        //private TableUserInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TableUserInfo
            //instance = new TableUserInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TableUserInfo
        /// </summary>
        [Test]
        public void TableUserInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TableUserInfo
            //Assert.IsInstanceOfType<TableUserInfo> (instance, "variable 'instance' is a TableUserInfo");
        }

        /// <summary>
        /// Test the property 'TableNumber'
        /// </summary>
        [Test]
        public void TableNumberTest()
        {
            // TODO unit test for the property 'TableNumber'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CustomerName'
        /// </summary>
        [Test]
        public void CustomerNameTest()
        {
            // TODO unit test for the property 'CustomerName'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Test]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }
        /// <summary>
        /// Test the property 'Areas'
        /// </summary>
        [Test]
        public void AreasTest()
        {
            // TODO unit test for the property 'Areas'
        }
        /// <summary>
        /// Test the property 'HighChair'
        /// </summary>
        [Test]
        public void HighChairTest()
        {
            // TODO unit test for the property 'HighChair'
        }
        /// <summary>
        /// Test the property 'Stroller'
        /// </summary>
        [Test]
        public void StrollerTest()
        {
            // TODO unit test for the property 'Stroller'
        }
        /// <summary>
        /// Test the property 'Party'
        /// </summary>
        [Test]
        public void PartyTest()
        {
            // TODO unit test for the property 'Party'
        }
        /// <summary>
        /// Test the property 'Vip'
        /// </summary>
        [Test]
        public void VipTest()
        {
            // TODO unit test for the property 'Vip'
        }
        /// <summary>
        /// Test the property 'GroupSize'
        /// </summary>
        [Test]
        public void GroupSizeTest()
        {
            // TODO unit test for the property 'GroupSize'
        }
        /// <summary>
        /// Test the property 'RegistrationId'
        /// </summary>
        [Test]
        public void RegistrationIdTest()
        {
            // TODO unit test for the property 'RegistrationId'
        }
        /// <summary>
        /// Test the property 'ReservationId'
        /// </summary>
        [Test]
        public void ReservationIdTest()
        {
            // TODO unit test for the property 'ReservationId'
        }
        /// <summary>
        /// Test the property 'WaitingId'
        /// </summary>
        [Test]
        public void WaitingIdTest()
        {
            // TODO unit test for the property 'WaitingId'
        }
        /// <summary>
        /// Test the property 'PartyTypes'
        /// </summary>
        [Test]
        public void PartyTypesTest()
        {
            // TODO unit test for the property 'PartyTypes'
        }
        /// <summary>
        /// Test the property 'CustomerProfile'
        /// </summary>
        [Test]
        public void CustomerProfileTest()
        {
            // TODO unit test for the property 'CustomerProfile'
        }
        /// <summary>
        /// Test the property 'ReservationTime'
        /// </summary>
        [Test]
        public void ReservationTimeTest()
        {
            // TODO unit test for the property 'ReservationTime'
        }

    }

}
