/* 
 * Qa full api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: all
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;

namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing TableAvailability
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TableAvailabilityTests
    {
        // TODO uncomment below to declare an instance variable for TableAvailability
        //private TableAvailability instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TableAvailability
            //instance = new TableAvailability();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TableAvailability
        /// </summary>
        [Test]
        public void TableAvailabilityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TableAvailability
            //Assert.IsInstanceOfType<TableAvailability> (instance, "variable 'instance' is a TableAvailability");
        }

        /// <summary>
        /// Test the property 'MinCoversRequired'
        /// </summary>
        [Test]
        public void MinCoversRequiredTest()
        {
            // TODO unit test for the property 'MinCoversRequired'
        }
        /// <summary>
        /// Test the property 'Reservable'
        /// </summary>
        [Test]
        public void ReservableTest()
        {
            // TODO unit test for the property 'Reservable'
        }
        /// <summary>
        /// Test the property 'Hours'
        /// </summary>
        [Test]
        public void HoursTest()
        {
            // TODO unit test for the property 'Hours'
        }

    }

}
