/* 
 * Qa full api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: all
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;

namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing TimeDimension
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TimeDimensionTests
    {
        // TODO uncomment below to declare an instance variable for TimeDimension
        //private TimeDimension instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TimeDimension
            //instance = new TimeDimension();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TimeDimension
        /// </summary>
        [Test]
        public void TimeDimensionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TimeDimension
            //Assert.IsInstanceOfType<TimeDimension> (instance, "variable 'instance' is a TimeDimension");
        }

        /// <summary>
        /// Test the property 'Hour'
        /// </summary>
        [Test]
        public void HourTest()
        {
            // TODO unit test for the property 'Hour'
        }
        /// <summary>
        /// Test the property 'WeekDay'
        /// </summary>
        [Test]
        public void WeekDayTest()
        {
            // TODO unit test for the property 'WeekDay'
        }
        /// <summary>
        /// Test the property 'WeekDayNumber'
        /// </summary>
        [Test]
        public void WeekDayNumberTest()
        {
            // TODO unit test for the property 'WeekDayNumber'
        }
        /// <summary>
        /// Test the property 'Month'
        /// </summary>
        [Test]
        public void MonthTest()
        {
            // TODO unit test for the property 'Month'
        }
        /// <summary>
        /// Test the property 'MonthNumber'
        /// </summary>
        [Test]
        public void MonthNumberTest()
        {
            // TODO unit test for the property 'MonthNumber'
        }
        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Test]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'WeekNumber'
        /// </summary>
        [Test]
        public void WeekNumberTest()
        {
            // TODO unit test for the property 'WeekNumber'
        }
        /// <summary>
        /// Test the property 'TypeOfMeal'
        /// </summary>
        [Test]
        public void TypeOfMealTest()
        {
            // TODO unit test for the property 'TypeOfMeal'
        }

    }

}
