/* 
 * Qa full api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: all
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;

namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing WaitingsStatistic
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WaitingsStatisticTests
    {
        // TODO uncomment below to declare an instance variable for WaitingsStatistic
        //private WaitingsStatistic instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WaitingsStatistic
            //instance = new WaitingsStatistic();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WaitingsStatistic
        /// </summary>
        [Test]
        public void WaitingsStatisticInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WaitingsStatistic
            //Assert.IsInstanceOfType<WaitingsStatistic> (instance, "variable 'instance' is a WaitingsStatistic");
        }

        /// <summary>
        /// Test the property 'InList'
        /// </summary>
        [Test]
        public void InListTest()
        {
            // TODO unit test for the property 'InList'
        }
        /// <summary>
        /// Test the property 'Called'
        /// </summary>
        [Test]
        public void CalledTest()
        {
            // TODO unit test for the property 'Called'
        }
        /// <summary>
        /// Test the property 'TablesAvailable'
        /// </summary>
        [Test]
        public void TablesAvailableTest()
        {
            // TODO unit test for the property 'TablesAvailable'
        }
        /// <summary>
        /// Test the property 'TotalCovers'
        /// </summary>
        [Test]
        public void TotalCoversTest()
        {
            // TODO unit test for the property 'TotalCovers'
        }
        /// <summary>
        /// Test the property 'CoversAvalible'
        /// </summary>
        [Test]
        public void CoversAvalibleTest()
        {
            // TODO unit test for the property 'CoversAvalible'
        }
        /// <summary>
        /// Test the property 'OneTwoGroup'
        /// </summary>
        [Test]
        public void OneTwoGroupTest()
        {
            // TODO unit test for the property 'OneTwoGroup'
        }
        /// <summary>
        /// Test the property 'ThreeFourGroup'
        /// </summary>
        [Test]
        public void ThreeFourGroupTest()
        {
            // TODO unit test for the property 'ThreeFourGroup'
        }
        /// <summary>
        /// Test the property 'FiveSixGroup'
        /// </summary>
        [Test]
        public void FiveSixGroupTest()
        {
            // TODO unit test for the property 'FiveSixGroup'
        }

    }

}
