/* 
 * Qa full api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: all
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;

namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing WaitingsStatDimensions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WaitingsStatDimensionsTests
    {
        // TODO uncomment below to declare an instance variable for WaitingsStatDimensions
        //private WaitingsStatDimensions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WaitingsStatDimensions
            //instance = new WaitingsStatDimensions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WaitingsStatDimensions
        /// </summary>
        [Test]
        public void WaitingsStatDimensionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WaitingsStatDimensions
            //Assert.IsInstanceOfType<WaitingsStatDimensions> (instance, "variable 'instance' is a WaitingsStatDimensions");
        }

        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'GroupSize'
        /// </summary>
        [Test]
        public void GroupSizeTest()
        {
            // TODO unit test for the property 'GroupSize'
        }
        /// <summary>
        /// Test the property 'TopSize'
        /// </summary>
        [Test]
        public void TopSizeTest()
        {
            // TODO unit test for the property 'TopSize'
        }
        /// <summary>
        /// Test the property 'LinePosition'
        /// </summary>
        [Test]
        public void LinePositionTest()
        {
            // TODO unit test for the property 'LinePosition'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
