using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;

namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing CustomerProfile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CustomerProfileTests
    {
        private CustomerProfile instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CustomerProfile();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of CustomerProfile
        /// </summary>
        [Test]
        public void CustomerProfileInstanceTest()
        {
            Assert.IsInstanceOf<CustomerProfile> (instance, "instance is a CustomerProfile");
        }

        /// <summary>
        /// Test the property 'LastVisitDate' 
        /// </summary>
        [Test]
        public void LastVisitDateTest()
        {
            // TODO: unit test for the property 'LastVisitDate' 
        }
        /// <summary>
        /// Test the property 'PhoneNumber' 
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO: unit test for the property 'PhoneNumber' 
        }
        /// <summary>
        /// Test the property 'VisitsCount' 
        /// </summary>
        [Test]
        public void VisitsCountTest()
        {
            // TODO: unit test for the property 'VisitsCount' 
        }
        /// <summary>
        /// Test the property 'FullName' 
        /// </summary>
        [Test]
        public void FullNameTest()
        {
            // TODO: unit test for the property 'FullName' 
        }
        /// <summary>
        /// Test the property 'Status' 
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO: unit test for the property 'Status' 
        }
        /// <summary>
        /// Test the property 'MembershipLevel' 
        /// </summary>
        [Test]
        public void MembershipLevelTest()
        {
            // TODO: unit test for the property 'MembershipLevel' 
        }
        /// <summary>
        /// Test the property 'Points' 
        /// </summary>
        [Test]
        public void PointsTest()
        {
            // TODO: unit test for the property 'Points' 
        }

    }

}
