using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;



namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing IEdmModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IEdmModelTests
    {
        private IEdmModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new IEdmModel();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of IEdmModel
        /// </summary>
        [Test]
        public void IEdmModelInstanceTest()
        {
            Assert.IsInstanceOf<IEdmModel> (instance, "instance is a IEdmModel");
        }

        
        /// <summary>
        /// Test the property 'SchemaElements' 
        /// </summary>
        [Test]
        public void SchemaElementsTest()
        {
            // TODO: unit test for the property 'SchemaElements' 
        }
        
        /// <summary>
        /// Test the property 'VocabularyAnnotations' 
        /// </summary>
        [Test]
        public void VocabularyAnnotationsTest()
        {
            // TODO: unit test for the property 'VocabularyAnnotations' 
        }
        
        /// <summary>
        /// Test the property 'ReferencedModels' 
        /// </summary>
        [Test]
        public void ReferencedModelsTest()
        {
            // TODO: unit test for the property 'ReferencedModels' 
        }
        
        /// <summary>
        /// Test the property 'DirectValueAnnotationsManager' 
        /// </summary>
        [Test]
        public void DirectValueAnnotationsManagerTest()
        {
            // TODO: unit test for the property 'DirectValueAnnotationsManager' 
        }
        

    }

}


