using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;

namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing IEdmVocabularyAnnotation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IEdmVocabularyAnnotationTests
    {
        private IEdmVocabularyAnnotation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new IEdmVocabularyAnnotation();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of IEdmVocabularyAnnotation
        /// </summary>
        [Test]
        public void IEdmVocabularyAnnotationInstanceTest()
        {
            Assert.IsInstanceOf<IEdmVocabularyAnnotation> (instance, "instance is a IEdmVocabularyAnnotation");
        }

        /// <summary>
        /// Test the property 'Qualifier' 
        /// </summary>
        [Test]
        public void QualifierTest()
        {
            // TODO: unit test for the property 'Qualifier' 
        }
        /// <summary>
        /// Test the property 'Term' 
        /// </summary>
        [Test]
        public void TermTest()
        {
            // TODO: unit test for the property 'Term' 
        }
        /// <summary>
        /// Test the property 'Target' 
        /// </summary>
        [Test]
        public void TargetTest()
        {
            // TODO: unit test for the property 'Target' 
        }

    }

}
