using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;



namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing LoyaltySettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoyaltySettingsTests
    {
        private LoyaltySettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new LoyaltySettings();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of LoyaltySettings
        /// </summary>
        [Test]
        public void LoyaltySettingsInstanceTest()
        {
            Assert.IsInstanceOf<LoyaltySettings> (instance, "instance is a LoyaltySettings");
        }

        
        /// <summary>
        /// Test the property 'CheckinPoints' 
        /// </summary>
        [Test]
        public void CheckinPointsTest()
        {
            // TODO: unit test for the property 'CheckinPoints' 
        }
        
        /// <summary>
        /// Test the property 'IsEnabled' 
        /// </summary>
        [Test]
        public void IsEnabledTest()
        {
            // TODO: unit test for the property 'IsEnabled' 
        }
        
        /// <summary>
        /// Test the property 'MembershipLevelRules' 
        /// </summary>
        [Test]
        public void MembershipLevelRulesTest()
        {
            // TODO: unit test for the property 'MembershipLevelRules' 
        }
        
        /// <summary>
        /// Test the property 'PurchasePointsRules' 
        /// </summary>
        [Test]
        public void PurchasePointsRulesTest()
        {
            // TODO: unit test for the property 'PurchasePointsRules' 
        }
        
        /// <summary>
        /// Test the property 'SignupPoints' 
        /// </summary>
        [Test]
        public void SignupPointsTest()
        {
            // TODO: unit test for the property 'SignupPoints' 
        }
        
        /// <summary>
        /// Test the property 'WaitingPointsRules' 
        /// </summary>
        [Test]
        public void WaitingPointsRulesTest()
        {
            // TODO: unit test for the property 'WaitingPointsRules' 
        }
        

    }

}


