using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;

namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing MembershipVisitItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MembershipVisitItemTests
    {
        private MembershipVisitItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new MembershipVisitItem();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of MembershipVisitItem
        /// </summary>
        [Test]
        public void MembershipVisitItemInstanceTest()
        {
            Assert.IsInstanceOf<MembershipVisitItem> (instance, "instance is a MembershipVisitItem");
        }

        /// <summary>
        /// Test the property 'Areas' 
        /// </summary>
        [Test]
        public void AreasTest()
        {
            // TODO: unit test for the property 'Areas' 
        }
        /// <summary>
        /// Test the property 'Table' 
        /// </summary>
        [Test]
        public void TableTest()
        {
            // TODO: unit test for the property 'Table' 
        }
        /// <summary>
        /// Test the property 'GroupSize' 
        /// </summary>
        [Test]
        public void GroupSizeTest()
        {
            // TODO: unit test for the property 'GroupSize' 
        }
        /// <summary>
        /// Test the property 'VisitDate' 
        /// </summary>
        [Test]
        public void VisitDateTest()
        {
            // TODO: unit test for the property 'VisitDate' 
        }

    }

}
