using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;



namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing ModelError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelErrorTests
    {
        private ModelError instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ModelError();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of ModelError
        /// </summary>
        [Test]
        public void ModelErrorInstanceTest()
        {
            Assert.IsInstanceOf<ModelError> (instance, "instance is a ModelError");
        }

        
        /// <summary>
        /// Test the property 'Exception' 
        /// </summary>
        [Test]
        public void ExceptionTest()
        {
            // TODO: unit test for the property 'Exception' 
        }
        
        /// <summary>
        /// Test the property 'ErrorMessage' 
        /// </summary>
        [Test]
        public void ErrorMessageTest()
        {
            // TODO: unit test for the property 'ErrorMessage' 
        }
        

    }

}


