using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;



namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing NewRemoteWaitingBindingModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NewRemoteWaitingBindingModelTests
    {
        private NewRemoteWaitingBindingModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new NewRemoteWaitingBindingModel();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of NewRemoteWaitingBindingModel
        /// </summary>
        [Test]
        public void NewRemoteWaitingBindingModelInstanceTest()
        {
            Assert.IsInstanceOf<NewRemoteWaitingBindingModel> (instance, "instance is a NewRemoteWaitingBindingModel");
        }

        
        /// <summary>
        /// Test the property 'RestaurantId' 
        /// </summary>
        [Test]
        public void RestaurantIdTest()
        {
            // TODO: unit test for the property 'RestaurantId' 
        }
        
        /// <summary>
        /// Test the property 'ReservationTime' 
        /// </summary>
        [Test]
        public void ReservationTimeTest()
        {
            // TODO: unit test for the property 'ReservationTime' 
        }
        
        /// <summary>
        /// Test the property 'CustomerName' 
        /// </summary>
        [Test]
        public void CustomerNameTest()
        {
            // TODO: unit test for the property 'CustomerName' 
        }
        
        /// <summary>
        /// Test the property 'GroupSize' 
        /// </summary>
        [Test]
        public void GroupSizeTest()
        {
            // TODO: unit test for the property 'GroupSize' 
        }
        
        /// <summary>
        /// Test the property 'NotificationUrl' 
        /// </summary>
        [Test]
        public void NotificationUrlTest()
        {
            // TODO: unit test for the property 'NotificationUrl' 
        }
        
        /// <summary>
        /// Test the property 'DeviceType' 
        /// </summary>
        [Test]
        public void DeviceTypeTest()
        {
            // TODO: unit test for the property 'DeviceType' 
        }
        
        /// <summary>
        /// Test the property 'Areas' 
        /// </summary>
        [Test]
        public void AreasTest()
        {
            // TODO: unit test for the property 'Areas' 
        }
        
        /// <summary>
        /// Test the property 'Note' 
        /// </summary>
        [Test]
        public void NoteTest()
        {
            // TODO: unit test for the property 'Note' 
        }
        
        /// <summary>
        /// Test the property 'HighChair' 
        /// </summary>
        [Test]
        public void HighChairTest()
        {
            // TODO: unit test for the property 'HighChair' 
        }
        
        /// <summary>
        /// Test the property 'Stroller' 
        /// </summary>
        [Test]
        public void StrollerTest()
        {
            // TODO: unit test for the property 'Stroller' 
        }
        

    }

}


