using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;



namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing ODataPagedResult1TransactionContract
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ODataPagedResult1TransactionContractTests
    {
        private ODataPagedResult1TransactionContract instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ODataPagedResult1TransactionContract();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of ODataPagedResult1TransactionContract
        /// </summary>
        [Test]
        public void ODataPagedResult1TransactionContractInstanceTest()
        {
            Assert.IsInstanceOf<ODataPagedResult1TransactionContract> (instance, "instance is a ODataPagedResult1TransactionContract");
        }

        
        /// <summary>
        /// Test the property 'Results' 
        /// </summary>
        [Test]
        public void ResultsTest()
        {
            // TODO: unit test for the property 'Results' 
        }
        
        /// <summary>
        /// Test the property 'Count' 
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO: unit test for the property 'Count' 
        }
        

    }

}


