using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;



namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing OnlineAvailability
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OnlineAvailabilityTests
    {
        private OnlineAvailability instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new OnlineAvailability();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of OnlineAvailability
        /// </summary>
        [Test]
        public void OnlineAvailabilityInstanceTest()
        {
            Assert.IsInstanceOf<OnlineAvailability> (instance, "instance is a OnlineAvailability");
        }

        
        /// <summary>
        /// Test the property 'AcceptReservations' 
        /// </summary>
        [Test]
        public void AcceptReservationsTest()
        {
            // TODO: unit test for the property 'AcceptReservations' 
        }
        
        /// <summary>
        /// Test the property 'AvailabilityLevel' 
        /// </summary>
        [Test]
        public void AvailabilityLevelTest()
        {
            // TODO: unit test for the property 'AvailabilityLevel' 
        }
        
        /// <summary>
        /// Test the property 'Open' 
        /// </summary>
        [Test]
        public void OpenTest()
        {
            // TODO: unit test for the property 'Open' 
        }
        
        /// <summary>
        /// Test the property 'RequestedTime' 
        /// </summary>
        [Test]
        public void RequestedTimeTest()
        {
            // TODO: unit test for the property 'RequestedTime' 
        }
        
        /// <summary>
        /// Test the property 'Time' 
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO: unit test for the property 'Time' 
        }
        

    }

}


