using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;



namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing OrderByClause
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderByClauseTests
    {
        private OrderByClause instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new OrderByClause();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of OrderByClause
        /// </summary>
        [Test]
        public void OrderByClauseInstanceTest()
        {
            Assert.IsInstanceOf<OrderByClause> (instance, "instance is a OrderByClause");
        }

        
        /// <summary>
        /// Test the property 'ThenBy' 
        /// </summary>
        [Test]
        public void ThenByTest()
        {
            // TODO: unit test for the property 'ThenBy' 
        }
        
        /// <summary>
        /// Test the property 'Expression' 
        /// </summary>
        [Test]
        public void ExpressionTest()
        {
            // TODO: unit test for the property 'Expression' 
        }
        
        /// <summary>
        /// Test the property 'Direction' 
        /// </summary>
        [Test]
        public void DirectionTest()
        {
            // TODO: unit test for the property 'Direction' 
        }
        
        /// <summary>
        /// Test the property 'RangeVariable' 
        /// </summary>
        [Test]
        public void RangeVariableTest()
        {
            // TODO: unit test for the property 'RangeVariable' 
        }
        
        /// <summary>
        /// Test the property 'ItemType' 
        /// </summary>
        [Test]
        public void ItemTypeTest()
        {
            // TODO: unit test for the property 'ItemType' 
        }
        

    }

}


