using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;



namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing PurchaseToPoints
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PurchaseToPointsTests
    {
        private PurchaseToPoints instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PurchaseToPoints();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of PurchaseToPoints
        /// </summary>
        [Test]
        public void PurchaseToPointsInstanceTest()
        {
            Assert.IsInstanceOf<PurchaseToPoints> (instance, "instance is a PurchaseToPoints");
        }

        
        /// <summary>
        /// Test the property 'FlatPoints' 
        /// </summary>
        [Test]
        public void FlatPointsTest()
        {
            // TODO: unit test for the property 'FlatPoints' 
        }
        
        /// <summary>
        /// Test the property 'MaxAmount' 
        /// </summary>
        [Test]
        public void MaxAmountTest()
        {
            // TODO: unit test for the property 'MaxAmount' 
        }
        
        /// <summary>
        /// Test the property 'Method' 
        /// </summary>
        [Test]
        public void MethodTest()
        {
            // TODO: unit test for the property 'Method' 
        }
        
        /// <summary>
        /// Test the property 'MinAmount' 
        /// </summary>
        [Test]
        public void MinAmountTest()
        {
            // TODO: unit test for the property 'MinAmount' 
        }
        
        /// <summary>
        /// Test the property 'PointsPerCent' 
        /// </summary>
        [Test]
        public void PointsPerCentTest()
        {
            // TODO: unit test for the property 'PointsPerCent' 
        }
        

    }

}


