using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;

namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing RedeemRequestReject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RedeemRequestRejectTests
    {
        private RedeemRequestReject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RedeemRequestReject();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of RedeemRequestReject
        /// </summary>
        [Test]
        public void RedeemRequestRejectInstanceTest()
        {
            Assert.IsInstanceOf<RedeemRequestReject> (instance, "instance is a RedeemRequestReject");
        }

        /// <summary>
        /// Test the property 'Reason' 
        /// </summary>
        [Test]
        public void ReasonTest()
        {
            // TODO: unit test for the property 'Reason' 
        }

    }

}
