using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;



namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing ReservationSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReservationSettingsTests
    {
        private ReservationSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ReservationSettings();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of ReservationSettings
        /// </summary>
        [Test]
        public void ReservationSettingsInstanceTest()
        {
            Assert.IsInstanceOf<ReservationSettings> (instance, "instance is a ReservationSettings");
        }

        
        /// <summary>
        /// Test the property 'AvailabilityMethod' 
        /// </summary>
        [Test]
        public void AvailabilityMethodTest()
        {
            // TODO: unit test for the property 'AvailabilityMethod' 
        }
        
        /// <summary>
        /// Test the property 'ConfirmationMessageRequestTemplate' 
        /// </summary>
        [Test]
        public void ConfirmationMessageRequestTemplateTest()
        {
            // TODO: unit test for the property 'ConfirmationMessageRequestTemplate' 
        }
        
        /// <summary>
        /// Test the property 'CoversAvailableForWait' 
        /// </summary>
        [Test]
        public void CoversAvailableForWaitTest()
        {
            // TODO: unit test for the property 'CoversAvailableForWait' 
        }
        
        /// <summary>
        /// Test the property 'CoversAvaliableForReservation' 
        /// </summary>
        [Test]
        public void CoversAvaliableForReservationTest()
        {
            // TODO: unit test for the property 'CoversAvaliableForReservation' 
        }
        
        /// <summary>
        /// Test the property 'DefaultMaxCoversPerSlot' 
        /// </summary>
        [Test]
        public void DefaultMaxCoversPerSlotTest()
        {
            // TODO: unit test for the property 'DefaultMaxCoversPerSlot' 
        }
        
        /// <summary>
        /// Test the property 'EnableAutoScheduling' 
        /// </summary>
        [Test]
        public void EnableAutoSchedulingTest()
        {
            // TODO: unit test for the property 'EnableAutoScheduling' 
        }
        
        /// <summary>
        /// Test the property 'IsEnabled' 
        /// </summary>
        [Test]
        public void IsEnabledTest()
        {
            // TODO: unit test for the property 'IsEnabled' 
        }
        
        /// <summary>
        /// Test the property 'MaxCoversPerSlotExceptions' 
        /// </summary>
        [Test]
        public void MaxCoversPerSlotExceptionsTest()
        {
            // TODO: unit test for the property 'MaxCoversPerSlotExceptions' 
        }
        
        /// <summary>
        /// Test the property 'MaxMinutesLate' 
        /// </summary>
        [Test]
        public void MaxMinutesLateTest()
        {
            // TODO: unit test for the property 'MaxMinutesLate' 
        }
        
        /// <summary>
        /// Test the property 'MaxPartySize' 
        /// </summary>
        [Test]
        public void MaxPartySizeTest()
        {
            // TODO: unit test for the property 'MaxPartySize' 
        }
        
        /// <summary>
        /// Test the property 'MiniutesToConfirm' 
        /// </summary>
        [Test]
        public void MiniutesToConfirmTest()
        {
            // TODO: unit test for the property 'MiniutesToConfirm' 
        }
        
        /// <summary>
        /// Test the property 'MinPartySize' 
        /// </summary>
        [Test]
        public void MinPartySizeTest()
        {
            // TODO: unit test for the property 'MinPartySize' 
        }
        
        /// <summary>
        /// Test the property 'MinutesToNotifyManager' 
        /// </summary>
        [Test]
        public void MinutesToNotifyManagerTest()
        {
            // TODO: unit test for the property 'MinutesToNotifyManager' 
        }
        
        /// <summary>
        /// Test the property 'RequireReservationConfirmation' 
        /// </summary>
        [Test]
        public void RequireReservationConfirmationTest()
        {
            // TODO: unit test for the property 'RequireReservationConfirmation' 
        }
        
        /// <summary>
        /// Test the property 'ReservationEmail' 
        /// </summary>
        [Test]
        public void ReservationEmailTest()
        {
            // TODO: unit test for the property 'ReservationEmail' 
        }
        
        /// <summary>
        /// Test the property 'ReservationHours' 
        /// </summary>
        [Test]
        public void ReservationHoursTest()
        {
            // TODO: unit test for the property 'ReservationHours' 
        }
        
        /// <summary>
        /// Test the property 'ReservationHoursStep' 
        /// </summary>
        [Test]
        public void ReservationHoursStepTest()
        {
            // TODO: unit test for the property 'ReservationHoursStep' 
        }
        
        /// <summary>
        /// Test the property 'ReservationInboxEmail' 
        /// </summary>
        [Test]
        public void ReservationInboxEmailTest()
        {
            // TODO: unit test for the property 'ReservationInboxEmail' 
        }
        
        /// <summary>
        /// Test the property 'StatusMessages' 
        /// </summary>
        [Test]
        public void StatusMessagesTest()
        {
            // TODO: unit test for the property 'StatusMessages' 
        }
        
        /// <summary>
        /// Test the property 'TableTurnOver' 
        /// </summary>
        [Test]
        public void TableTurnOverTest()
        {
            // TODO: unit test for the property 'TableTurnOver' 
        }
        
        /// <summary>
        /// Test the property 'TableTurnOverByGroup' 
        /// </summary>
        [Test]
        public void TableTurnOverByGroupTest()
        {
            // TODO: unit test for the property 'TableTurnOverByGroup' 
        }
        
        /// <summary>
        /// Test the property 'TotalCovers' 
        /// </summary>
        [Test]
        public void TotalCoversTest()
        {
            // TODO: unit test for the property 'TotalCovers' 
        }
        

    }

}


