using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;

namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing SingleValueNode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SingleValueNodeTests
    {
        private SingleValueNode instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SingleValueNode();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of SingleValueNode
        /// </summary>
        [Test]
        public void SingleValueNodeInstanceTest()
        {
            Assert.IsInstanceOf<SingleValueNode> (instance, "instance is a SingleValueNode");
        }

        /// <summary>
        /// Test the property 'TypeReference' 
        /// </summary>
        [Test]
        public void TypeReferenceTest()
        {
            // TODO: unit test for the property 'TypeReference' 
        }
        /// <summary>
        /// Test the property 'Kind' 
        /// </summary>
        [Test]
        public void KindTest()
        {
            // TODO: unit test for the property 'Kind' 
        }

    }

}
