using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;



namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing UpdateReservationBindingModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateReservationBindingModelTests
    {
        private UpdateReservationBindingModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UpdateReservationBindingModel();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of UpdateReservationBindingModel
        /// </summary>
        [Test]
        public void UpdateReservationBindingModelInstanceTest()
        {
            Assert.IsInstanceOf<UpdateReservationBindingModel> (instance, "instance is a UpdateReservationBindingModel");
        }

        
        /// <summary>
        /// Test the property 'ReservationId' 
        /// </summary>
        [Test]
        public void ReservationIdTest()
        {
            // TODO: unit test for the property 'ReservationId' 
        }
        
        /// <summary>
        /// Test the property 'PhoneNumber' 
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO: unit test for the property 'PhoneNumber' 
        }
        
        /// <summary>
        /// Test the property 'ReservationTime' 
        /// </summary>
        [Test]
        public void ReservationTimeTest()
        {
            // TODO: unit test for the property 'ReservationTime' 
        }
        
        /// <summary>
        /// Test the property 'GroupSize' 
        /// </summary>
        [Test]
        public void GroupSizeTest()
        {
            // TODO: unit test for the property 'GroupSize' 
        }
        
        /// <summary>
        /// Test the property 'Areas' 
        /// </summary>
        [Test]
        public void AreasTest()
        {
            // TODO: unit test for the property 'Areas' 
        }
        
        /// <summary>
        /// Test the property 'Note' 
        /// </summary>
        [Test]
        public void NoteTest()
        {
            // TODO: unit test for the property 'Note' 
        }
        
        /// <summary>
        /// Test the property 'HighChair' 
        /// </summary>
        [Test]
        public void HighChairTest()
        {
            // TODO: unit test for the property 'HighChair' 
        }
        
        /// <summary>
        /// Test the property 'Stroller' 
        /// </summary>
        [Test]
        public void StrollerTest()
        {
            // TODO: unit test for the property 'Stroller' 
        }
        

    }

}


