using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HostMe.Sdk.Api;
using HostMe.Sdk.Model;
using HostMe.Sdk.Client;
using System.Reflection;



namespace HostMe.Sdk.Test
{
    /// <summary>
    ///  Class for testing WaitingReportItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WaitingReportItemTests
    {
        private WaitingReportItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new WaitingReportItem();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of WaitingReportItem
        /// </summary>
        [Test]
        public void WaitingReportItemInstanceTest()
        {
            Assert.IsInstanceOf<WaitingReportItem> (instance, "instance is a WaitingReportItem");
        }

        
        /// <summary>
        /// Test the property 'Status' 
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO: unit test for the property 'Status' 
        }
        
        /// <summary>
        /// Test the property 'Created' 
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO: unit test for the property 'Created' 
        }
        
        /// <summary>
        /// Test the property 'GroupSize' 
        /// </summary>
        [Test]
        public void GroupSizeTest()
        {
            // TODO: unit test for the property 'GroupSize' 
        }
        
        /// <summary>
        /// Test the property 'StartPosition' 
        /// </summary>
        [Test]
        public void StartPositionTest()
        {
            // TODO: unit test for the property 'StartPosition' 
        }
        
        /// <summary>
        /// Test the property 'TimeToCall' 
        /// </summary>
        [Test]
        public void TimeToCallTest()
        {
            // TODO: unit test for the property 'TimeToCall' 
        }
        
        /// <summary>
        /// Test the property 'TimeToSeat' 
        /// </summary>
        [Test]
        public void TimeToSeatTest()
        {
            // TODO: unit test for the property 'TimeToSeat' 
        }
        
        /// <summary>
        /// Test the property 'TimeToCancel' 
        /// </summary>
        [Test]
        public void TimeToCancelTest()
        {
            // TODO: unit test for the property 'TimeToCancel' 
        }
        

    }

}


