/* 
 * Qa full api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: all
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace HostMe.Sdk.Model
{
    /// <summary>
    /// FloorInfo
    /// </summary>
    [DataContract]
    public partial class FloorInfo :  IEquatable<FloorInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FloorInfo" /> class.
        /// </summary>
        /// <param name="FloorId">FloorId.</param>
        /// <param name="Name">Name.</param>
        /// <param name="FloorUrl">FloorUrl.</param>
        public FloorInfo(string FloorId = null, string Name = null, string FloorUrl = null)
        {
            this.FloorId = FloorId;
            this.Name = Name;
            this.FloorUrl = FloorUrl;
        }
        
        /// <summary>
        /// Gets or Sets FloorId
        /// </summary>
        [DataMember(Name="floorId", EmitDefaultValue=true)]
        public string FloorId { get; set; }
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=true)]
        public string Name { get; set; }
        /// <summary>
        /// Gets or Sets FloorUrl
        /// </summary>
        [DataMember(Name="floorUrl", EmitDefaultValue=true)]
        public string FloorUrl { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FloorInfo {\n");
            sb.Append("  FloorId: ").Append(FloorId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  FloorUrl: ").Append(FloorUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as FloorInfo);
        }

        /// <summary>
        /// Returns true if FloorInfo instances are equal
        /// </summary>
        /// <param name="other">Instance of FloorInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FloorInfo other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.FloorId == other.FloorId ||
                    this.FloorId != null &&
                    this.FloorId.Equals(other.FloorId)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.FloorUrl == other.FloorUrl ||
                    this.FloorUrl != null &&
                    this.FloorUrl.Equals(other.FloorUrl)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.FloorId != null)
                    hash = hash * 59 + this.FloorId.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.FloorUrl != null)
                    hash = hash * 59 + this.FloorUrl.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}